development:
  adapter: postgresql
  database: connectst_dev
  encoding: utf8
  username: ljrzarate
  password: dev
  host: 127.0.0.1

test: &TEST
  adapter: postgresql
  database: connectst_test
  encoding: utf8
  username: ljrzarate
  password: dev
  host: 127.0.0.1

production:
  adapter: postgresql
  database: connectst_production
